### ISSUE TITLE
osx-razer-led problem with xcode

### ISSUE THREAD

**Issue by DocSystem** [kprinssu/osx-razer-blade#3]
I'm trying to create an application that uses [osx-razer-led](https://github.com/dylanparker/osx-razer-led) to manage the Razer Blade keyboard. But when I click on the button that execute the program, it says me Unable to create plugin (0xe00002be).
Here is my code:
```swift
import Cocoa

var brightnessValue: Int = 255
var colorValue: NSColor = NSColor.white
var nsColor:NSColor = colorValue
var ciColor:CIColor = CIColor(color: nsColor)!
var redColorValue: Int = Int()
var greenColorValue: Int = Int()
var blueColorValue: Int = Int()

@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {

    @IBOutlet weak var window: NSWindow!


    func applicationDidFinishLaunching(_ aNotification: Notification) {
        // Insert code here to initialize your application
    }

    func applicationWillTerminate(_ aNotification: Notification) {
        // Insert code here to tear down your application
    }
    
    @IBOutlet weak var brightness: NSSlider!
    @IBAction func brightnessUpdated(_ sender: NSSlider) {
        brightnessValue = Int(sender.intValue)
    }
    
    @IBOutlet weak var color: NSColorWell!
    @IBAction func colorUpdated(_ sender: NSColorWell) {
        colorValue = sender.color
        nsColor = colorValue
        ciColor = CIColor(color: nsColor)!
        redColorValue = Int(ciColor.red * 255)
        greenColorValue = Int(ciColor.green * 255)
        blueColorValue = Int(ciColor.blue * 255)

    }
    
    
    @IBAction func applyBacklight(_ sender: NSButton) {
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/usr/bin/osx-razer-led")
        task.arguments = ["brightness \(brightnessValue)"]
        task.launch()
    }
    
    @IBAction func applyColor(_ sender: NSButton) {
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/usr/bin/osx-razer-led")
        task.arguments = ["color \(redColorValue) \(greenColorValue) \(blueColorValue)"]
        task.launch()
    }
}
```

**Comment by kprinssu** [comment]
@DocSystem This seems like an issue with your code. Please provide more context, where and when does the error occur? Runtime, compile time? What exactly causes the error?

**Comment by DocSystem** [comment]
The error occurs on runtime, when I click on the Apply button.
I'm trying to make a GUI to manage my Razer keyboard, here is the Xcode project:
[Blade Keyboard.zip](https://github.com/kprinssu/osx-razer-blade/files/4503148/Blade.Keyboard.zip)
Thanks for your help

**Comment by kprinssu** [comment]
I don't have a Razer device on hand to test but the error seems like it's not related to this project and more on Objective C frontend. Right of the bat, running your code gives delegate errors in console. I suggest you use Stackoverflow.

I am not trying to brush you off, but I have other higher priority projects that I am currently working on. I suggest you Google the error and spend time debugging it on your own.

**Comment by DocSystem** [comment]
I totally understand you have higher priorities! I’m a developer and I also have priorities
I already asked it on stackoverflow but had no answer: https://stackoverflow.com/questions/60835794/xcode-returns-unable-to-create-plugin-0xe00002be-while-running-external-execut
I already googled it but found no corresponding things. I will try to debug it myself! Thanks for your help!

**Comment by kprinssu** [comment]
@DocSystem I think you should look @1kc's implementation, https://github.com/1kc/razer-macos

It has nice frontend UI for projects like this one.
